### PR TITLE
Fix setup.py missing package_data

### PR DESCRIPTION
**Pull request by qbx2**
@niftools/pyffi-reviewer 

# Overview
setup.py is not including the package data

## Fixes Known Issues
n\a

## Documentation
[Overview of updates to documentation]

## Testing
[Overview of testing required to ensure functionality is correctly implemented]

### Manual
[Order steps to manually verify updates are working correctly]

### Automated
[List of tests run, updated or added to avoid future regressions]

## Additional Information
Caused by  #53 update which didn't reconnect the package_data attribute

### CODE REVIEW

**Comment by neomonkeus** [comment]
I actually see this manifest as a downstream dependency not working as intended when using the pypi version. Going to deploy and see if it resolved that issue for me also.

**Comment by neomonkeus** [comment]
I have merged some changes to get the build automation back up an running.
If you rebase the branch that would be helpful as there is no way through the github ui to retrigger the build. Going to rebase this branch locally and build a release.

**Comment by qbx2** [comment]
Did that work?

**Comment by neomonkeus** [comment]
The force push triggered the build, but looks like you haven't rebased the branch so it built using the broken config fixed by #55. 
I ended up building it locally to test and uploaded it to Pypi, as wanted to get rid of the universal wheel 
that was already there as we don't support py2 anyways.

I did some additional local testing with Blender upstream using the new version as a dependency and it failed miserably. This is not entirely unexpected as Blender is coupled to an older version anyways.
Two things of note 
- Camelcase issues eg. ApplyMode enum used to have underscores and now doesn't. I need to check if there was a change in the nif.xml or pyffi expression parse around member generation. Not a big issue, but dont want to update the Blender code and then have to undo it again if is a bug in pyffi.
- Seeing lots of read issues, which is usually a indication that there is type mismatches, 
I might update to a newer version of the nif.xml and requiring merging in some of the other open PRs.

Anyways this PR is certainly not the cause of the above issues so going to merge it in.

**Comment by neomonkeus** [comment]
This is comparison between what blender is using and this version - https://github.com/niftools/pyffi/compare/niftools:887fe13610e8cdec96d1f67993acae1159e2e440...niftools:develop#diff-0e48de255873b7fbfcd0c291d00203e7R87

I think I have found the enum issue.
Will require futher investigation to see if there is an underlying nif.xml issue. https://github.com/niftools/nifxml/compare/959cb9c3dd59a319e60e819fc8a1402f821f3684...f265c56482c728c6877e45d5b5993d3bff83670a
I suspect the version that pyffi is currently using is just broken. It should really be updated to latest version but updates to meta-data parsing is required.

**Pull request merged**
