### PR TITLE
Removed calls for the bs num uv set to match changes in nif xml

### PR DESCRIPTION
**Pull request by Ghostwalker71**

### CODE REVIEW

**Comment by Ghostwalker71** [comment]
I can create another pull to set the submodules pointing at the master branches. I hadn't noticed that either as I rarely even look at master. As for the diff, I honestly have no idea what that is all about.

**Comment by neomonkeus** [comment]
This is all the changes between the commit pyffi was pointing to and nifxml develop latest. - https://github.com/niftools/nifxml/compare/3ad328e8c493da1e0358231fe6fd2a20237351d7...niftools:develop

If updating the commit pointer in a pull request, the accompany changes need to also be included.

**Comment by Ghostwalker71** [comment]
Would it not be easier to branch off of master and force update develop then I can generate a new commit and pull for the sub-modules links? There have been no pull requests other than mine.

**Comment by Ghostwalker71** [comment]
Rebased and ready to merge, I've tested the changes thoroughly and am confident they are correct.

**Comment by Ghostwalker71** [comment]
Until this is merged I will be unable to move forward on any further edits to the plugin, so when you find the time to actually look it over and realize that it does work, merge it then send me a message. If I'm not involved elsewhere I will see about making further advancements to the plugin.

**Pull request merged**
